[package]
name = "webhook-server"
description = "A simple web server to easily execute scripts/executables on incoming requests."
version = "0.1.5-alpha.0"
authors = ["Arne Beer <contact@arne.beer>"]
repository = "https://github.com/nukesor/webhook-server"
homepage = "https://github.com/nukesor/webhook-server"
documentation = "https://docs.rs/webhook-server"
license = "MIT"
keywords = ["webhook", "server", "script", "executor", "https"]
readme = "README.md"
edition = "2018"

[[bin]]
name = "webhookserver"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustls = "0.18"
async-std = { version = "1", features = ["attributes", "std"] }
actix-web = { version = "3", features=["rustls"]}
handlebars = "3"
chrono = { version = "0.4", features = ["serde"] }

config = "0.10"
dirs = "3"
anyhow = "1"
log = "0.4"
simplelog = "0.9"

pueue-lib = "0.11"

serde = "1"
serde_yaml = "0.8"
serde_json = "1"

hex = "0.4"
hmac = "0.10"
sha-1 = "0.9"
base64 = "0.13"
