name: Linting

on:
  push:
    banches:
      - main
  pull_request:
    banches:
      - main

jobs:
  build:
    name: Test building for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
          components: clippy

      - name: cargo clippy
        run: cargo clippy --tests --workspace -- -D warnings

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: ${{ matrix.target }}
          components: rustfmt

      - name: cargo fmt
        run: cargo +nightly fmt --all -- --check
