name: Packaging

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # This should work with only the `include`s but it currently doesn't because of this bug:
        # https://github.community/t5/How-to-use-Git-and-GitHub/GitHub-Actions-Matrix-options-dont-work-as-documented/td-p/29558
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            artifact_name: webhookserver
            release_name: webhookserver-linux-amd64
          - os: windows-latest
            artifact_name: webhookserver.exe
            release_name: webhookserver-windows-amd64.exe
          - os: macos-latest
            artifact_name: webhookserver
            release_name: webhookserver-macos-amd64

    steps:
      - uses: hecrj/setup-rust-action@v2
        with:
          rust-version: stable
      - uses: actions/checkout@v4

      - name: Run tests
        run: cargo test --verbose

      - name: Build the binary
        run: cargo build --release --locked
      - uses: svenstaro/upx-action@2.4.1
        with:
          file: target/release/${{ matrix.artifact_name }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@2.9.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.release_name }}
          tag: ${{ github.ref }}
