name: Tests

on:
  push:
    banches: -master
  pull_request:

jobs:
  build:
    name: Test building for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: hecrj/setup-rust-action@v2
        with:
          rust-version: stable
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
