name: Tests

on:
  push:
    banches:
      - main
  pull_request:
    banches:
      - main

jobs:
  build:
    name: Test building for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
